theme: jekyll-theme-cayman
show_downloads: true
title: OpenAPI JavaScript Sample Repository
tagline: Saxo Bank OpenAPI samples in JavaScript
author: Saxo Bank
email: openapisupport@saxobank.com
description: "Examples of OpenAPI interactions in JavaScript demonstrating common usage patterns"
keywords: "Saxo Bank OpenAPI JavaScript Samples Examples"
favicon: "/openapi-samples-js/favicon.ico"
